# This is a basic workflow to help you get started with Actions

name: CI

on: 
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'     
        required: true
      reponame:
        description: 'Repository name'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo ${{ github.event.inputs.project }} ${{ github.event.inputs.reponame }}
        
      - name: Create repository
        run: gh repo create ${{ github.event.inputs.reponame }} --public --disable-wiki --disable-issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
