# This is a basic workflow to help you get started with Actions

name: CI

on: 
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'     
        required: true
      reponame:
        description: 'Repository name'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo ${{ github.event.inputs.project }} ${{ github.event.inputs.reponame }}
        
      - run: gh api --method POST -H "Accept: application/vnd.github.v3+json" /orgs/frederikvannoote/repos 
  -f name='${{ github.event.inputs.reponame }}'
 -F private=false
 -F has_issues=true
 -F has_projects=true
 -F has_wiki=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
